version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: attendix-postgres
    restart: always
    environment:
      POSTGRES_DB: attendix_db
      POSTGRES_USER: attendix
      POSTGRES_PASSWORD: gj@attendix
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - attendix-net

  attendix-backend:
    image: attendix-backend:1.0
    container_name: attendix-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "18090:8080"
    environment:
      ATTENDIX_RESOURCE_SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendix_db
      SPRING_DATASOURCE_USERNAME: attendix
      SPRING_DATASOURCE_PASSWORD: gj@attendix
      ATTENDIX_FIREBASE_LOCATION: /app/firebase.json
    volumes:
      - /etc/attendix/firebase.json:/app/firebase.json:ro
    networks:
      - attendix-net

  attendix-auth:
    image: attendix-auth:1.0
    container_name: attendix-auth
    restart: always
    depends_on:
      - postgres
    ports:
      - "18081:8081"
    environment:
      ATTENDIX_AUTH_SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendix_db
      SPRING_DATASOURCE_USERNAME: attendix
      SPRING_DATASOURCE_PASSWORD: gj@attendix
      ATTENDIX_FIREBASE_LOCATION: /app/firebase.json
    volumes:
      - /etc/attendix/firebase.json:/app/firebase.json:ro
    networks:
      - attendix-net

volumes:
  pgdata:

networks:
  attendix-net:
    driver: bridge
